### ISSUE TITLE
what_defined, pub_moduledoc

### ISSUE THREAD

**Issue by ghost** [msoedov/firex#1]
# Firex not function in my version of Elixir 1.4.4.

![screenshot_20170620_175137](https://user-images.githubusercontent.com/10014721/27342915-c3b97222-55e1-11e7-9536-4bf555267f65.png)
![screenshot_20170620_175243](https://user-images.githubusercontent.com/10014721/27342925-c846db7c-55e1-11e7-85b0-c69c64ef995c.png)

## With

![screenshot_mix exs](https://user-images.githubusercontent.com/10014721/27343033-09e016ac-55e2-11e7-8bb5-7d734fe2dd9c.png)

**Comment by ghost** [comment]
@msoedov I have fork the project for try to correct the problem my-self.

**Comment by msoedov** [comment]
@ZackEyston Thanks for the report. I have not tested it with 14.4 yet but with 14.4 it worked fine:
https://travis-ci.org/msoedov/firex . I will take a look to this a bit latter

**Comment by ghost** [comment]
@msoedov Okay, thx, I think it's cause by nil in to_op_types. I work it.

**Comment by msoedov** [comment]
@ZackEyston any patch will be appreciated :)

**Comment by ghost** [comment]
Okay, i have correct the wraning  and correct the bug :)

**Comment by ghost** [comment]
I have make a pull request, you can close this if all stuff is correct.

**Comment by msoedov** [comment]
@ZackEyston Thanks for contribution, I have added 1.4.4 to travis build matrix

**Comment by ghost** [comment]
@msoedov Thx too, Firex is useful :+1: , and correct the version of Firex in README please, haha :)

**Comment by ghost** [comment]
@msoedov  So, if you check my pull request, close this issue. :)
